#!/bin/bash
clear
BLACK="\033[0;30m"  
DARK_GRAY="\033[1;30m"  
BLUE="\033[0;34m"  
LIGHT_BLUE="\033[1;34m"  
GREEN="\033[0;32m"  
LIGHT_GREEN="\033[1;32m"  
CYAN="\033[0;36m"  
LIGHT_CYAN="\033[1;36m"  
RED="\033[0;31m"  
LIGHT_RED="\033[1;31m"  
PURPLE="\033[0;35m"  
LIGHT_PURPLE="\033[1;35m"  
BROWN="\033[0;33m"  
YELLOW="\033[0;33m"  
LIGHT_GRAY="\033[0;37m"  
WHITE="\033[1;37m" 
NC="\033[0m"

echo ""
echo ""

parentPath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parentPath"
appPath=$( find "$parentPath" -name '*.app' -maxdepth 1)
appName=${appPath##*/}
appBashName=${appName// /\ }
appDIR="/Applications/${appBashName}"
echo ""
echo ""
echo -e "Fix tool for '${appBashName} is damaged and cannot be opened / from an unidentified developer' issues"
echo ""
# Prompt to install if the app is missing; if installed, bypass notarization
if [ ! -d "$appDIR" ];then
  echo ""
  echo -e "Result: ${RED}${appBashName} is not installed yet, please install it first${NC}"
  else
  # Bypass notarization
  echo -e "${YELLOW}Enter your login password, then press Return (the password is invisible while typing)${NC}"
  sudo spctl --master-disable
  sudo xattr -rd com.apple.quarantine /Applications/"$appBashName"
  echo ""
  echo ""
  echo -e "Result: ${GREEN}Repair successful!${NC} You can now run ${appBashName} normally."
fi
echo ""
echo ""
echo -e "You can close this window now!"